# Data Description:
The detailed data dictionary is given below:

- Suburb - Suburb in which the property is located
- Rooms - Number of rooms in the property
- Type - Type of the property like
    h - house,cottage,villa, semi,terrace,
    t - townhouse,
- u - unit, duplex
- SellerG - Name of the real estate agent who sold the property
- Date - Date on which the property was sold
- Distance - Distance of the property from CBD in kilometres. CBD is the central business district of the city.
- Postcode - Postcode of the area
- Bedroom - Number of bedrooms in the property
- Bathroom - Number of bathrooms in the property
- Car - Number of car parking spaces in the property
- Landsize - Size of the land in square metres
- BuildingArea - Size of the building in square metres (Generally, building size is smaller than land size since someone can have personal gardens and other things in the property.)
- YearBuilt - Year in which the building was built
- Regionname - Name of the region in which the property is located like - Eastern Metropolitan, Western Metropolitan, Northern Victoria etc.
- Propertycount - Number of properties that are present in the suburb
- Price - price (in AUD) at which the property was sold

#### Sanity Check

##### Importing libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.float_format', lambda x : '%.3f'% x)  # float value to 3 decimal places

In [ ]:
filepath ='/content/drive/MyDrive/Edgeverve datasets/Melbourne_Housing-1.csv'

##### Importing Dataset

In [ ]:
data = pd.read_csv(filepath)

##### view the first and last 5 rows of the data

In [ ]:
data.head(10)

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
0,Airport West,3,t,Nelson,03-09-2016,13.500,3042.000,3.000,2.000,1.000,303.000,225,2016.000,Western Metropolitan,3464,840000
1,Albert Park,2,h,hockingstuart,03-09-2016,3.300,3206.000,2.000,1.000,0.000,120.000,82,1900.000,Southern Metropolitan,3280,1275000
2,Albert Park,2,h,Thomson,03-09-2016,3.300,3206.000,2.000,1.000,0.000,159.000,inf,NaN,Southern Metropolitan,3280,1455000
3,Alphington,4,h,Brace,03-09-2016,6.400,3078.000,3.000,2.000,4.000,853.000,263,1930.000,Northern Metropolitan,2211,2000000
4,Alphington,3,h,Jellis,03-09-2016,6.400,3078.000,3.000,2.000,2.000,208.000,inf,2013.000,Northern Metropolitan,2211,1110000
5,Altona,3,h,Greg,03-09-2016,13.800,3018.000,3.000,2.000,1.000,352.000,242,2015.000,Western Metropolitan,5301,520000
6,Altona North,5,h,FN,03-09-2016,11.100,3025.000,5.000,3.000,6.000,592.000,251,1965.000,Western Metropolitan,5132,1085000
7,Altona North,3,h,Jas,03-09-2016,11.100,3025.000,3.000,1.000,2.000,533.000,117,1970.000,Western Metropolitan,5132,781000
8,Altona North,4,h,hockingstuart,03-09-2016,11.100,3025.000,NaN,NaN,NaN,NaN,missing,NaN,Western Metropolitan,5132,857500
9,Armadale,2,u,Jellis,03-09-2016,6.300,3143.000,2.000,1.000,1.000,50.000,76,1964.000,Southern Metropolitan,4836,599000

In [ ]:
data.tail()

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
27109,Noble Park,3,h,C21,30-09-2017,22.700,3174.000,3.000,1.000,6.000,569.000,130,1959.000,South-Eastern Metropolitan,11806,627500
27110,Reservoir,3,u,RW,30-09-2017,12.000,3073.000,3.000,1.000,1.000,NaN,105,1990.000,Northern Metropolitan,21650,475000
27111,Roxburgh Park,4,h,Raine,30-09-2017,20.600,3064.000,4.000,2.000,2.000,NaN,225,1995.000,Northern Metropolitan,5833,591000
27112,Springvale South,3,h,Harcourts,30-09-2017,22.200,3172.000,3.000,2.000,1.000,544.000,NaN,NaN,South-Eastern Metropolitan,4054,780500
27113,Westmeadows,4,h,Barry,30-09-2017,16.500,3049.000,4.000,2.000,6.000,813.000,140,1960.000,Northern Metropolitan,2474,791000

##### Understand the shape of the data

In [ ]:
print(f'No of rows  {data.shape[0]}  No of columns  {data.shape[1]}')

No of rows  27114  No of columns  16

##### Check the datatype of columns for the dataset

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27114 entries, 0 to 27113
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27114 non-null  object
 1   Rooms          27114 non-null  int64
 2   Type           27114 non-null  object
 3   SellerG        27114 non-null  object
 4   Date           27114 non-null  object
 5   Distance       27113 non-null  float64
 6   Postcode       27113 non-null  float64
 7   Bedroom        20678 non-null  float64
 8   Bathroom       20672 non-null  float64
 9   Car            20297 non-null  float64
 10  Landsize       17873 non-null  float64
 11  BuildingArea   10543 non-null  object
 12  YearBuilt      11985 non-null  float64
 13  Regionname     27114 non-null  object
 14  Propertycount  27114 non-null  int64
 15  Price          27114 non-null  int64
dtypes: float64(7), int64(3), object(6)
memory usage: 3.3+ MB

- There are 10 numerical columns in the data and 6 object type columns.
- Date column being read as object type column but it should be in date- time format
- Building area is read as object column but it should be numeric

In [ ]:
# changing the datatype of date column
data['Date'] = pd.to_datetime(data['Date'] , format= "%d-%m-%Y")

In [ ]:
data['BuildingArea'].unique()

array(['225', '82', 'inf', '263', '242', '251', '117', 'missing', '76',
       '399', '118', '103', '180', '123', '218', '129', '167', '154',
       '275', '121', nan, '125', '255', '75', '156', '240', '268', '108',
       '69', '140', '214', '253', '189', '215', '96', '104', '100', '313',
       '144', '93', '110', '70', '122', '51', '147', '113', '83', '56',
       '137', '85', '64', '175', '3558', '170', '265', '353', '138', '19',
       '116', '87', '74', '320', '300', '210', '120', '86', '97', '200',
       '106', '14', '161', '128', '185', '146', '133', '115', '143',
       '150', '195', '236', '276', '188', '179', '249', '141', '34', '73',
       '107', '84', '81', '207', '50', '264', '312', '235', '221', '183',
       '132', '160', '186', '78', '105', '145', '62', '220', '315', '181',
       '61', '112', '420', '226', '266', '410', '449', '356', '477',
       '250', '95', '190', '284', '247', '213', '209', '119', '111',
       '130', '348', '166', '44', '176', '98', '159', '79', '71', '60',
       '33', '89', '217', '127', '187', '109', '53', '201', '12', '63',
       '223', '102', '254', '327', '16', '165', '65', '139', '134', '280',
       '67', '272', '38', '153', '66', '152', '135', '374', '163', '124',
       '233', '39', '151', '279', '136', '405', '199', '158', '126', '80',
       '57', '36', '142', '77', '435', '92', '149', '114', '349', '178',
       '594', '274', '40', '68', '164', '204', '94', '257', '323', '314',
       '378', '55', '91', '309', '88', '58', '172', '211', '148', '49',
       '52', '174', '191', '335', '808', '168', '203', '520', '212',
       '222', '171', '228', '101', '267', '90', '196', '157', '99', '256',
       '15', '155', '162', '72', '252', '330', '177', '341', '197', '340',
       '182', '245', '270', '42', '229', '232', '131', '297', '237',
       '194', '173', '46', '360', '205', '45', '365', '321', '37', '304',
       '54', '305', '244', '43', '41', '22', '169', '59', '258', '230',
       '287', '618', '792', '355', '202', '395', '351', '325', '248',
       '224', '426', '286', '308', '198', '260', '291', '277', '281',
       '216', '262', '364', '30', '192', '47', '184', '25', '558', '362',
       '375', '347', '241', '475', '413', '400', '101.37', '219', '239',
       '123.21', '140.7481', '86.5', '30.6', '225.5', '322', '409.54',
       '26', '156.6', '227.6', '104.63', '193', '443', '167.13', '148.5',
       '270.18', '53.3', '98.5', '157.9351', '328', '94.3', '21', '310',
       '95.88', '261', '105.7', '72.9', '45.4', '221.3', '113.2',
       '186.75', '540', '127.8', '231', '106.4', '311', '234', '332',
       '206', '259', '246', '296', '269', '306', '380', '302', '48',
       '278', '35', '208', '467', '283', '458', '196.8', '106.2', '32',
       '424', '430', '243', '290', '511', '500', '531', '508', '333',
       '72.3', '66.23', '101.51', '292', '112.9', '99.5', '77.5', '293',
       '105.23', '352', '391', '121.8', '82.6', '136.49', '502', '680',
       '157.9352', '126.8', '100.6', '44.4', '151.54', '20', '397', '495',
       '331', '294', '334', '303', '318', '273', '584', '958', '288',
       '342', '354', '350', '465', '337', '317', '298', '529', '697',
       '289', '602', '6791', '534', '227', '429', '802', '373', '358',
       '238', '316', '393', '180.9', '826.8367', '366', '307', '625',
       '419', '94.5', '392', '28', '116.65', '11', '134.6', '282',
       '183.84', '431', '126.7', '18', '295', '390', '447', '271', '416',
       '370', '660', '463', '361', '496', '324', '173.45', '134.3',
       '464.3', '76.77', '113.76', '107.4', '255.79', '186.36', '490',
       '103.6', '63.7', '106.76', '39.5', '423', '319', '437', '285',
       '453', '472', '418', '487', '31', '301', '116.4', '182.85',
       '109.5', '129.7', '665', '398', '148.47', '553', '182.9', '184.75',
       '193.74', '68.5', '336', '346', '719', '3112', '414', '372', '525',
       '367', '1561', '454', '720', '329', '381', '677', '439', '857',
       '23', '503', '432', '377', '512', '425', '406', '389', '521',
       '6178', '654', '727', '417', '560', '168.01', '306.19', '515.78',
       '196.1', '789', '131.27', '167.87', '183.97', '199.5', '29', '446',
       '75.45', '165.5', '263.5', '585', '516', '345', '27', '444', '427',
       '326', '518', '13', '411', '1022', '339', '461', '376', '513',
       '836', '464', '386', '603', '613', '179.3', '142.6', '147.2',
       '225.98', '113.81', '401', '737', '530', '82.3', '110.87', '450',
       '673', '109.98', '122.25', '105.9', '101.7', '106.9', '93.82',
       '132.6', '154.3', '178.74', '88.3', '80.7', '89.25', '181.6',
       '104.4', '180.56', '123.5', '1143', '506', '575', '859', '653',
       '999', '445', '438', '686', '649', '736', '371.6122', '199.73',
       '118.54', '298.21', '169.5', '42.2', '135.5', '266.76', '272.4',
       '177.8', '139.4', '700', '766', '538', '528', '650', '368', '544',
       '557', '396', '638', '101.76', '363', '634', '195.0964', '470',
       '130.52', '547', '111.04', '63.4', '92.5', '115.96', '121.84',
       '122.86', '114.2', '266.53', '78.54', '85.35', '1041', '607',
       '478', '407', '344', '338', '501', '448', '357', '408', '412',
       '466', '739', '614', '421', '385', '68.11', '153.1', '85.2',
       '93.84', '124.45', '210.68', '200.71', '81.79', '934', '129.92',
       '43.7', '113.6', '66.32', '35.64', '61.6', '388.5', '672'],
      dtype=object)

In [ ]:
# No of unique building area values
data['BuildingArea'].nunique()

655

In [ ]:
# checking the count of different data types in building area columns
data['BuildingArea'] .apply(type).value_counts()

BuildingArea
<class 'float'>    16571
<class 'str'>      10543
Name: count, dtype: int64

- we can see there are mixed data types value in building area columns like missing , inf , which should be read as missing value NAN .Let replace such data points with null values

In [ ]:
# replace values with nan
data['BuildingArea'] = data['BuildingArea'].replace(['missing','inf'],np.nan)
# change data type to float
data['BuildingArea'] = data['BuildingArea'].astype(float)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27103 entries, 0 to 27102
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27103 non-null  object
 1   Rooms          27103 non-null  int64
 2   Type           27103 non-null  object
 3   SellerG        27103 non-null  object
 4   Date           27103 non-null  datetime64[ns]
 5   Distance       27102 non-null  float64
 6   Postcode       27102 non-null  float64
 7   Bedroom        20678 non-null  float64
 8   Bathroom       20672 non-null  float64
 9   Car            20297 non-null  float64
 10  Landsize       17873 non-null  float64
 11  BuildingArea   10529 non-null  float64
 12  YearBuilt      11985 non-null  float64
 13  Regionname     27103 non-null  object
 14  Propertycount  27103 non-null  int64
 15  Price          27103 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(3), object(4)
memory usage: 3.3+ MB

##### Checking for missing values in the data

In [ ]:
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom           6425
Bathroom          6431
Car               6806
Landsize          9230
BuildingArea     16574
YearBuilt        15118
Regionname           0
Propertycount        0
Price                0
dtype: int64

##### checking for duplicate entries in the data

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
# remove duplicate enteries from the data
data.drop_duplicates(inplace=True)

In [ ]:
# reset the index of data frame since rows have been removed
data.reset_index(drop=True,inplace=True)